### ISSUE TITLE
AUTH_PERSIST_ERROR

### ISSUE THREAD

**Issue by baoshan** [baoshan/cloudkit.js#1]
From a quick-n-dirty debugging, I find Apple use `path=` rather than `path=/` when setting their cookie. Which will make the `setUpAuth` fail on pages from different paths.

**Comment by karthyPeriyasamy** [comment]
The cookie **path=/** will not using when a different route path, instead cloudkit js prodcing another cookie with same name in different route with differerent path like **path=/works**. And when try to fetch or auth using cloudkit js, then an error will thrown "AUTH_PERSIST_ERROR, can't read and write ckSession"
